version: "3.8"
services:
  web:
    build: .
    ports:
      - "8080:80"
  db:
    ports:
      - "5432:5432"
    image: postgres:13.13-bullseye
    restart: always
    environment: 
      POSTGRES_PASSWORD: example
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/
  pathfinder:
    ports:
      - "8090:8090"
    build: ./pathfinder

volumes:
  database:
